name: CI for PRs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with: 
      dotnet-version: 6.x
      
     - name: Restore dependencies
       run: dotnet restore

      - name: Run StyleCop Linter
        run: dotnet build --no-incremental --verbosity: minimal

        
  lint:
  
      runs-on: ubuntu-latest

steps:
      uses: actions/checkout@v2

     - name: Super-Linter
    uses: github/super-linter@v7.1.0
    env:
        VALIDATE_CPP: true         
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
